version: '3'

services:
  botService:
    container_name: TgsRenderBotService
    build: ./
    image: tgs-render-bot
    volumes:
      - "./config.json:/config.json:ro"
      - "./cache:/cache"
    restart: always
    environment:
      - REDIS_URL=redis://TgsRenderBotRedis:6379
      - RENDER_API=http://TgsRenderBotRenderer:8000
  redis:
    container_name: TgsRenderBotRedis
    image: redis
    restart: always
  rlottie-to-gif-api:
    container_name: TgsRenderBotRenderer
    build: ./rlottie-to-gif-api
    image: rlottie-to-gif-api
    restart: always